### ISSUE TITLE
Astra documents: some documents go to 404 Error to show them in non-English language

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/astra-family#4]
Page: [Intro to the Astra family](https://docs.netapp.com/us-en/astra-family/intro-family.html)
Hi, there are the language filters in all documents for Astra, but selecting a language shows 404 Error instead of localized pages for some documents.

**Comment by netapp-gudugunti** [comment]
Thanks! for the feedback @yukakou. Work is in progress to enable localized content. Shall update you as soon as the localized content is available.

**Comment by netapp-gudugunti** [comment]
The issue is resolved. Localized content is available.
